version: '3.8'
services:
  postgres-database:
    image: postgres:16.0
    container_name: z1_db
    restart: always
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=super
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    #     secrets:
    #       - secretKey

    #   backend:
    #     build:
    #       context: ../Z1-Backend
    #       dockerfile: Dockerfile
    #     container_name: z1_backend1
    #     depends_on:
    #       - postgres-database
    #     restart: unless-stopped
    #     environment:
    #       - DB_HOST=postgres-database
    #     ports:
    #       - 8080:8080
    #     secrets:
    #       - secretKey

    # secrets:
    #   secretKey:
    #     file: secretKey.txt
